networks:
  itmo:

services:

  database:
    image: postgres:latest
    container_name: web4_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tpupa
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: area_checker
    networks:
      - itmo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - itmo
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target:/opt/jboss/wildfly/standalone/deployments/
    environment:
      DB_USER: tpupa
      DB_PASSWORD: postgres
      DB_NAME: area_checker
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - itmo
    ports:
      - "3200:80"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - itmo
